import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f7f7fb',
  },
  screen: {
    flex: 1,
    padding: 18,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  card: {
    backgroundColor: '#fff',
    margin: 18,
    padding: 18,
    borderRadius: 16,
    gap: 12,
    shadowColor: '#2a2a2a',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 20,
    elevation: 3,
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: '#161616',
  },
  muted: {
    color: '#6b6b78',
  },
  mutedSmall: {
    color: '#6b6b78',
    fontSize: 12,
    marginTop: 6,
  },
  error: {
    color: '#b01b1b',
    fontWeight: '600',
  },
  input: {
    borderWidth: 1,
    borderColor: '#d2d2dd',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#fff',
  },
  button: {
    backgroundColor: '#1d4ed8',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  buttonDisabled: {
    backgroundColor: '#91a7ff',
  },
  buttonText: {
    color: '#fff',
    fontWeight: '600',
  },
  buttonSecondarySmall: {
    alignSelf: 'flex-start',
    backgroundColor: '#eef2ff',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginTop: 8,
  },
  buttonSecondaryText: {
    color: '#1d4ed8',
    fontWeight: '600',
    fontSize: 12,
  },
  link: {
    color: '#1d4ed8',
    fontWeight: '600',
  },
  linkHint: {
    color: '#1d4ed8',
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  valueButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    backgroundColor: '#eef2ff',
    borderWidth: 1,
    borderColor: '#c7d2fe',
  },
  valueButtonText: {
    color: '#1d4ed8',
    fontWeight: '700',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerSpacer: {
    width: 40,
  },
  scopeSelector: {
    backgroundColor: '#fff',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    marginBottom: 12,
    shadowColor: '#2a2a2a',
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 2,
  },
  scopeSelectorLabel: {
    fontSize: 12,
    color: '#6b6b78',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  scopeSelectorValue: {
    marginTop: 4,
    fontSize: 14,
    fontWeight: '700',
    color: '#1d4ed8',
  },
  beSwitcher: {
    minWidth: 56,
    paddingHorizontal: 10,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#eef1ff',
  },
  beSwitcherText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1d4ed8',
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    marginRight: 8,
    shadowColor: '#2a2a2a',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 2,
  },
  menuIcon: {
    fontSize: 18,
    color: '#1d4ed8',
    fontWeight: '700',
  },
  headerBreadcrumb: {
    flex: 1,
    marginLeft: 14,
    marginRight: 8,
    paddingVertical: 4,
    color: '#6b6b78',
    fontSize: 12,
  },
  headerBreadcrumbSpacer: {
    flex: 1,
  },
  sectionTopSpacer: {
    height: 8,
  },
  homeButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    backgroundColor: '#eef2ff',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cartButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#eef2ff',
    borderWidth: 1,
    borderColor: '#c7d2fe',
  },
  cartButtonPulse: {
    backgroundColor: '#dbeafe',
    borderColor: '#93c5fd',
  },
  cartButtonText: {
    color: '#1d4ed8',
    fontWeight: '700',
  },
  cartBadge: {
    minWidth: 18,
    paddingHorizontal: 6,
    height: 18,
    borderRadius: 999,
    backgroundColor: '#1d4ed8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  cartFloating: {
    position: 'absolute',
    right: 18,
    top: 84,
    zIndex: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#eef2ff',
    borderWidth: 1,
    borderColor: '#c7d2fe',
    shadowColor: '#2a2a2a',
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 16,
    elevation: 5,
  },
  backButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    backgroundColor: '#e2e8f0',
  },
  backButtonIcon: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1d4ed8',
  },
  homeButtonIcon: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1d4ed8',
  },
  toggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: '#eef2ff',
  },
  toggleIcon: {
    fontSize: 12,
    color: '#1d4ed8',
    fontWeight: '700',
  },
  toggleLabel: {
    color: '#1d4ed8',
    fontWeight: '600',
  },
  sectionTitle: {
    marginTop: 18,
    fontSize: 14,
    fontWeight: '600',
    color: '#2a2a2a',
  },
  allocationsHeader: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  allocationsTitle: {
    marginTop: 0,
  },
  periodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 10,
  },
  periodList: {
    marginTop: 0,
  },
  periodListRow: {
    flex: 1,
  },
  periodListContent: {
    gap: 8,
  },
  periodTotal: {
    alignItems: 'flex-end',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: '#eef2ff',
    minWidth: 96,
  },
  periodTotalLabel: {
    fontSize: 11,
    color: '#4b5563',
    fontWeight: '600',
  },
  periodTotalValue: {
    fontSize: 18,
    color: '#1d4ed8',
    fontWeight: '700',
  },
  periodChip: {
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#d2d2dd',
  },
  periodChipActive: {
    backgroundColor: '#1d4ed8',
    borderColor: '#1d4ed8',
  },
  periodChipText: {
    fontWeight: '600',
    color: '#2a2a2a',
  },
  periodChipTextActive: {
    color: '#fff',
  },
  listCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 12,
    marginTop: 12,
  },
  placeholderTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1d4ed8',
    marginBottom: 6,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f4',
  },
  rowLabel: {
    flex: 1,
    color: '#2a2a2a',
  },
  rowAmount: {
    color: '#2a2a2a',
    fontWeight: '600',
  },
  menuBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  menuPanel: {
    backgroundColor: '#fff',
    padding: 18,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    gap: 12,
  },
  menuTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#161616',
  },
  menuItem: {
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#f2f4ff',
    alignItems: 'center',
  },
  menuItemActive: {
    backgroundColor: '#1d4ed8',
  },
  menuItemDanger: {
    backgroundColor: '#ffecec',
  },
  menuItemText: {
    fontWeight: '600',
    color: '#1d4ed8',
  },
  menuItemTextActive: {
    color: '#fff',
  },
  menuItemTextDanger: {
    color: '#b01b1b',
  },
  dashboardStack: {
    flexGrow: 1,
    marginTop: 12,
    paddingBottom: 24,
  },
  dashboardCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    shadowColor: '#2a2a2a',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1d4ed8',
    marginBottom: 6,
  },
  cardValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#161616',
  },
  cardSubtle: {
    fontSize: 12,
    color: '#6b6b78',
    marginTop: 4,
  },
  balanceGood: {
    color: '#16a34a',
    fontWeight: '700',
  },
  balanceBad: {
    color: '#dc2626',
    fontWeight: '700',
  },
  paymentButton: {
    marginTop: 8,
    alignSelf: 'flex-start',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#16a34a',
  },
  paymentButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 12,
  },
  cardRow: {
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f1f6',
  },
  cardRowInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cardRowTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1f2937',
  },
  cardRowMeta: {
    fontSize: 12,
    color: '#6b6b78',
    marginTop: 2,
  },
  pollRowTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pollStatusPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  pollStatusPillOk: {
    backgroundColor: '#dcfce7',
  },
  pollStatusPillWarn: {
    backgroundColor: '#fef3c7',
  },
  pollStatusPillNo: {
    backgroundColor: '#fee2e2',
  },
  pollStatusPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1f2937',
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
  },
  tagPill: {
    backgroundColor: '#eef2ff',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  tagText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1d4ed8',
  },
  optionRow: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    marginTop: 8,
  },
  optionRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  optionRowBadge: {
    fontSize: 11,
    color: '#1d4ed8',
    fontWeight: '700',
  },
  voteSummary: {
    marginTop: 10,
    padding: 10,
    backgroundColor: '#eef2ff',
    borderRadius: 10,
  },
  voteSummaryLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1d4ed8',
    marginBottom: 4,
  },
  voteSummaryText: {
    fontSize: 13,
    color: '#1f2937',
    fontWeight: '600',
  },
  voteActions: {
    marginTop: 12,
    gap: 8,
  },
  buttonGhost: {
    backgroundColor: '#eef2ff',
  },
  buttonGhostText: {
    color: '#1d4ed8',
    fontWeight: '600',
  },
  rsvpRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  rsvpButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#f3f4f6',
  },
  rsvpButtonActive: {
    backgroundColor: '#1d4ed8',
  },
  rsvpButtonGhost: {
    backgroundColor: '#eef2ff',
  },
  rsvpButtonText: {
    color: '#1f2937',
    fontWeight: '600',
  },
  rsvpButtonTextActive: {
    color: '#fff',
  },
  pushBanner: {
    backgroundColor: '#fef3c7',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  pushBannerText: {
    fontSize: 12,
    color: '#1f2937',
    fontWeight: '600',
  },
  optionRowSelected: {
    borderColor: '#1d4ed8',
    backgroundColor: '#eef2ff',
  },
  optionRowText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1f2937',
  },
  cardLinkRow: {
    marginTop: 8,
  },
  cardLinkText: {
    color: '#1d4ed8',
    fontWeight: '600',
  },
  statementSummary: {
    marginTop: 10,
    gap: 2,
  },
  statementDetail: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f4',
    paddingTop: 10,
    gap: 4,
  },
  statementSectionTitle: {
    marginTop: 8,
    fontSize: 12,
    fontWeight: '700',
    color: '#1f2937',
  },
  statementRow: {
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f4',
  },
  statementRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statementRowTitle: {
    fontSize: 11,
    fontWeight: '600',
    color: '#1f2937',
  },
  statementRowAmount: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1f2937',
  },
  cardLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  expensesList: {
    flex: 1,
  },
  expensesListContent: {
    paddingBottom: 24,
  },
  expensesHeader: {
    marginBottom: 12,
  },
  expenseSeparator: {
    height: 10,
  },
  expenseRowCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    shadowColor: '#2a2a2a',
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 8,
    elevation: 2,
  },
  expenseRowCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  expenseRowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  expenseDrillBlock: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f4',
    paddingTop: 10,
    gap: 8,
  },
  expenseDrillCard: {
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    padding: 10,
    gap: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  expenseDrillRowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  expenseDrillLabel: {
    flex: 1,
    color: '#1f2937',
    fontSize: 12,
    fontWeight: '600',
  },
  expenseDrillAmount: {
    color: '#1f2937',
    fontSize: 12,
    fontWeight: '600',
  },
  expenseDetailList: {
    gap: 8,
  },
  expenseDetailCard: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 8,
    gap: 4,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  expenseDetailLabel: {
    flex: 1,
    color: '#111827',
    fontSize: 12,
    fontWeight: '600',
  },
  expenseDetailAmount: {
    color: '#111827',
    fontSize: 12,
    fontWeight: '600',
  },
})
